INFO     HTTP CLIENT:event_hooks.py:20 Make POST request to http://localhost:8000/api/v1/users
INFO     HTTP CLIENT:event_hooks.py:24 GOT Response 200 OK from http://localhost:8000/api/v1/users
INFO     HTTP CLIENT:event_hooks.py:20 Make POST request to http://localhost:8000/api/v1/authentication/login
INFO     HTTP CLIENT:event_hooks.py:24 GOT Response 200 OK from http://localhost:8000/api/v1/authentication/login
INFO     HTTP CLIENT:event_hooks.py:20 Make POST request to http://localhost:8000/api/v1/files
INFO     HTTP CLIENT:event_hooks.py:24 GOT Response 200 OK from http://localhost:8000/api/v1/files
INFO     HTTP CLIENT:event_hooks.py:20 Make GET request to http://localhost:8000/api/v1/files/incorrect-file-id
INFO     HTTP CLIENT:event_hooks.py:24 GOT Response 422 Unprocessable Entity from http://localhost:8000/api/v1/files/incorrect-file-id
INFO     Base Assertions:base.py:16 Check that response status code equals to 422
INFO     Files Assertions:files.py:126 Check get file with incorrect file id response
INFO     Errors Assertions:errors.py:39 Check validation error response
INFO     Base Assertions:base.py:67 Check that length of "details" equals to 1
INFO     Errors Assertions:errors.py:18 Check validation error
INFO     Base Assertions:base.py:33 Check that "type" equals to uuid_parsing
INFO     Base Assertions:base.py:33 Check that "input" equals to incorrect-file-id
INFO     Base Assertions:base.py:33 Check that "context" equals to {'error': 'invalid character: expected an optional prefix of `urn:uuid:` followed by [0-9a-fA-F-], found `i` at 1'}
INFO     Base Assertions:base.py:33 Check that "message" equals to Input should be a valid UUID, invalid character: expected an optional prefix of `urn:uuid:` followed by [0-9a-fA-F-], found `i` at 1
INFO     Base Assertions:base.py:33 Check that "location" equals to ['path', 'file_id']
INFO     Validating JSON Schema:schema.py:20 Validating JSON schema